### ISSUE TITLE
Button configuration

### ISSUE THREAD

**Issue by souzagabriela** [paulohgs/CheckWeather#5]
Oi PH, 
Vi que tinha um comentário sobre button configuration, provavelmente sobre o butão não estar com o espaçamento correto. Nessa parte aqui:

https://github.com/paulohgs/CheckWeather/blob/0fa17e679e3903cf9cd98ccc297e9e1fd211a6da/CheckWeather/View/WeatherView.swift#L14-L20

Primeiro, de acordo com a própria documentação da Apple esse UIButton(type: .roundedRect) foi descontinuado.  link: https://developer.apple.com/documentation/uikit/uibutton/buttontype/1624029-roundedrect

Uma solução seria usar UIButton.configuration, nele contem todas as opções customizadas pro butão. Ficaria mais ou menos assim:

```swift
lazy var getButton = make(UIButton()) {   // -> aqui voce retira o type de dentro
        $0.configuration = .bordered()   // -> bem aqui 
        $0.setTitle("Get weather", for: .normal)
        $0.translatesAutoresizingMaskIntoConstraints = false
        $0.layer.cornerRadius = 5
        $0.backgroundColor = .white
    }
```

**Comment by paulohgs** [comment]
Tudo bom ella? Vi aqui o erro e corrigi ele, você pode observar a mudança no seguinte PR: https://github.com/paulohgs/CheckWeather/pull/7
Agradeço a contribuição!
