### ISSUE TITLE
Projeto de Arquitetura

### ISSUE THREAD

**Issue by stephane1809** [paulohgs/CheckWeather#6]
Bom diaa
Notei que no seu projeto os files AppDelegate.swift, SceneDelegate.swift e ViewController.swift estão diretamente na raiz do projeto, ou seja não estão dentro de nenhum arquivo (Group), para melhorar a arquitetura do seu projeto você pode criar dois arquivos, um chamado por exemplo de "ViewController", colocando o file ViewController.swift nele, e outro de "Delegate", colocando o AppDelegate.swift e o SceneDelegate.swift nele.

**Comment by paulohgs** [comment]
Oi Stephane, tudo bem? Acredito que você olhou apenas para minha branch `main`, mas acontece que meu desenvolvimento está sendo feito dentro de outra branch, a `develop`, porém não acabei indicando isso em meu README. Vou estar fechando a issue, mas agradeço a ajuda e se puder revisar o projeto na outra branch agradeço bastante, também estarei indicando isso na entrada do projeto.
